---
- name: Deploy example applications for testing cluster functionalities
  hosts: oo_all_hosts
  become: yes
  tasks:
  - name: Create resources in openshift cluster
    shell:
      cmd: |
        cat << EOF >> /etc/hosts
        172.25.5.2 iam-apigateway-proxy.fusioncloud.huawei.com
        172.25.5.2 iam-cache-proxy.fusioncloud.huawei.com
        172.25.5.2 ecs-api.fusioncloud.huawei.com
        172.25.5.2 evs-api.fusioncloud.huawei.com
        172.25.5.2 vpc-api.fusioncloud.huawei.com
        172.25.5.2 bms-api.fusioncloud.huawei.com
        172.25.5.2 ccs-api.fusioncloud.huawei.com
        172.25.5.2 as-api.fusioncloud.huawei.com
        172.25.5.2 ims-api.fusioncloud.huawei.com
        172.25.5.2 rts-api.fusioncloud.huawei.com
        172.25.5.2 rts.shenzhen-1.fusioncloud.huawei.com
        EOF
      executable: /bin/bash
