- hosts: all
  become: yes
  vars:
    job_uid: '{{ zuul.build[:10] }}'
  roles:
    - role: export-cloud-openrc
  tasks:
    - name: Run Openshift functional tests against {{ cloud_name }}
      shell:
        cmd: |
          set -e
          mkdir -p '{{ ansible_user_dir }}/src/github.com/huaweicloud/'
          cd '{{ ansible_user_dir }}/src/github.com/huaweicloud/'
          git clone http://github.com/huaweicloud/openshift-ansible
          cd openshift-ansible

          set -x
          pip install ansible
          pip install jinja2
          pip install shade
          pip install jmespath
          pip install dnspython
          pip install python-openstackclient
          pip install python-heatclient
          # shopt -s expand_aliases
          # alias openstack="openstack --insecure"

          openstack keypair delete openshift || true
          openstack keypair create openshift > openshift.pem
          chmod 400 ./openshift.pem
          . ./keystonerc

          # Check prerequisites
          ansible-playbook --user root \
              -i playbooks/openstack/inventory.py \
              -i "playbooks/openstack/{{ inventory_name }}-inventory" \
              --private-key "./openshift-{{ job_uid }}.pem" \
              playbooks/openstack/openshift-cluster/prerequisites.yml \
              -e @extra_vars.yml

          # Provision
          ansible-playbook --user root \
              -i playbooks/openstack/inventory.py \
              -i "playbooks/openstack/{{ inventory_name }}-inventory" \
              --private-key "./openshift-{{ job_uid }}.pem" \
              playbooks/openstack/openshift-cluster/provision.yml \
              -e @extra_vars.yml

          # Install openshift cluster
          ansible-playbook --user root \
              -i playbooks/openstack/inventory.py \
              -i "playbooks/openstack/{{ inventory_name }}-inventory" \
              --private-key "./openshift-{{ job_uid }}.pem"  \
              playbooks/openstack/openshift-cluster/install.yml \
              -e @extra_vars.yml

          # Testing openshift cluster functionalities
          ansible-playbook --user root \
              -i playbooks/openstack/inventory.py \
              -i "playbooks/openstack/{{ inventory_name }}-inventory" \
              --private-key "./openshift-{{ job_uid }}.pem"  \
              cluster-testing.yaml \
              -e @extra_vars.yml
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/src/github.com/huaweicloud/openshift-ansible'
      environment: '{{ global_env }}'
