- hosts: all
  become: yes
  roles:
    - role: export-cloud-openrc
      vars:
        cloud_name: 'fusioncloud'
  tasks:
    - name: workaround for fusioncloud domain name mapping
      shell:
        cmd: |
          cat << EOF >> /etc/hosts

          58.255.93.185 iam-apigateway-proxy.fusioncloud.huawei.com
          58.255.93.185 iam-cache-proxy.fusioncloud.huawei.com
          58.255.93.185 ecs.shenzhen-1.fusioncloud.huawei.com
          58.255.93.185 evs.shenzhen-1.fusioncloud.huawei.com
          58.255.93.185 vpc.shenzhen-1.fusioncloud.huawei.com
          58.255.93.185 bms.shenzhen-1.fusioncloud.huawei.com
          58.255.93.185 ccs.shenzhen-1.fusioncloud.huawei.com
          58.255.93.185 as.shenzhen-1.fusioncloud.huawei.com
          58.255.93.185 ims.shenzhen-1.fusioncloud.huawei.com
          58.255.93.185 rts.shenzhen-1.fusioncloud.huawei.com
          EOF
        executable: /bin/bash

    - name: Run Openshift functional tests against fusioncloud
      shell:
        cmd: |
          set -e
          set -x
          cd '{{ ansible_user_dir }}/src/github.com/openshift/openshift-ansible'
          pip install "ansible>=2.6.5,<2.7"
          ansible --version
          ansible-playbook -i inventory/hosts.localhost playbooks/prerequisites.yml
          sleep 7200
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ global_env }}'
