- hosts: all
  become: yes
  roles:
    - role: export-cloud-openrc
      vars:
        cloud_name: 'fusioncloud'

    - name: Create keystonerc for openshift-ansible
      shell:
        cmd: |
          cat << EOF >> keystonerc
          # set your own ENV in the file
          export OS_AUTH_URL={{ global_env.OS_AUTH_URL }}
          export OS_USERNAME={{ global_env.OS_USERNAME }}
          export OS_PASSWORD={{ global_env.OS_PASSWORD }}
          export OS_IDENTITY_API_VERSION={{ global_env.OS_IDENTITY_API_VERSION }}
          export OS_DOMAIN_NAME={{ global_env.OS_DOMAIN_NAME }}
          export OS_USER_DOMAIN_NAME={{ global_env.OS_DOMAIN_NAME }}
          export OS_PROJECT_DOMAIN_NAME={{ global_env.OS_DOMAIN_NAME }}
          export OS_TENANT_NAME={{ global_env.OS_TENANT_NAME }}
          export OS_REGION_NAME={{ global_env.OS_REGION_NAME }}
          export OS_AVAILABILITY_ZONE={{ global_env.OS_AVAILABILITY_ZONE }}
          EOF
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/src/github.com/huaweicloud/openshift-ansible'

    - name: Run Openshift functional tests against fusioncloud
      shell:
        cmd: |
          set -e
          set -x
          pip install -U python-openstackclient
          sleep 7200
          sed -i "/use_external_ip/ s|v3.9|{{ openshift_release }}|" playbooks/openstack/huawei-inventory/group_vars/OSEv3.yml

          . hack/install.sh
          # pip install "ansible>=2.6.5,<2.7"
          # ansible --version
          # ansible-playbook -i inventory/hosts.localhost playbooks/prerequisites.yml
          # sleep 7200
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/src/github.com/huaweicloud/openshift-ansible'
      environment: '{{ global_env }}'
