- hosts: all
  become: yes
  roles:
    - role: export-cloud-openrc
      vars:
        cloud_name: 'vexxhost'
  tasks:
    - name: Clean up resources for lbass octavia acceptance tests
      shell:
        cmd: |
          set -e
          set -x
          '{{ kubectl }}' config use-context local
          ext_lb_svc_uid=$('{{ kubectl }}' get services external-http-nginx-service -o=jsonpath='{.metadata.uid}') || true
          int_lb_svc_uid=$('{{ kubectl }}' get services internal-http-nginx-service -o=jsonpath='{.metadata.uid}') || true

          '{{ kubectl }}' delete -f examples/loadbalancers/internal-http-nginx.yaml || true
          '{{ kubectl }}' delete -f examples/loadbalancers/external-http-nginx.yaml || true

          for lb_svc_uid in $ext_lb_svc_uid $int_lb_svc_uid; do
              lb_name=$(echo $lb_svc_uid | tr -d '-' | sed 's/^/a/' | cut -c -32)
              {
                  for pool in $(openstack loadbalancer show $lb_name -f value -c pools); do
                      openstack loadbalancer pool delete $pool
                      sleep 2
                  done
                  for listener in $(openstack loadbalancer show $lb_name -f value -c listeners); do
                      openstack loadbalancer listener delete $listener
                      sleep 2
                  done
                  openstack loadbalancer delete $lb_name
                  sleep 2
              } || true
          done
        executable: /bin/bash
        chdir: '{{ k8s_os_provider_src_dir }}'
      environment: '{{ golang_env }}'
