- hosts: all
  become: yes
  roles:
    - role: export-cloud-openrc
      vars:
        cloud_name: 'vexxhost'
  tasks:
    - name: Clean up resources for kubernetes tests
      shell:
        cmd: |
          set -x
          pip install -U python-openstackclient

          server_id=$(python -c "import json;print json.load(open('/mnt/config/openstack/latest/meta_data.json', 'r'))['uuid']")
          pv_name=$('{{ kubectl }}' get pv | sed '1d' | awk '{print $1}')
          volume_id=$(openstack volume list | awk "/$pv_name/ {print \$2}")
          if [[ -n "$volume_id" ]]; then
              openstack server remove volume "$server_id" "$volume_id"
              openstack volume delete "$volume_id"
          fi
        executable: /bin/bash
        chdir: '{{ k8s_os_provider_src_dir }}'
      environment: '{{ golang_env }}'
      ignore_errors: yes
