- name: Register vexxhost openrc
  shell:
    cmd: |
      # use echo to delete extra spaces
      OS_AUTH_TYPE=$(echo '{{ vexxhost_credentials.auth_type }}')
      OS_IDENTITY_API_VERSION=$(echo '{{ vexxhost_credentials.identity_api_version }}')
      OS_VOLUME_API_VERSION=$(echo '{{ vexxhost_credentials.volume_api_version }}')
      OS_INTERFACE=$(echo '{{ vexxhost_credentials.interface }}')
      OS_AUTH_URL=$(echo '{{ vexxhost_credentials.auth_url }}')
      OS_PROJECT_ID=$(echo '{{ vexxhost_credentials.project_id }}')
      OS_PROJECT_NAME=$(echo '{{ vexxhost_credentials.project_name }}')
      OS_USER_DOMAIN_NAME=$(echo '{{ vexxhost_credentials.user_domain_name }}')
      OS_PROJECT_DOMAIN_ID=$(echo '{{ vexxhost_credentials.project_domain_id }}')
      OS_USERNAME=$(echo '{{ vexxhost_credentials.username }}')
      OS_PASSWORD=$(echo '{{ vexxhost_credentials.password }}')
      OS_REGION_NAME=$(echo '{{ vexxhost_credentials.region_name }}')

      # echo "{
      #     \"OS_AUTH_TYPE\": \"$OS_AUTH_TYPE\",
      #     \"OS_IDENTITY_API_VERSION\": \"$OS_IDENTITY_API_VERSION\",
      #     \"OS_VOLUME_API_VERSION\": \"$OS_VOLUME_API_VERSION\",
      #     \"OS_INTERFACE\": \"$OS_INTERFACE\",
      #     \"OS_AUTH_URL\": \"$OS_AUTH_URL\",
      #     \"OS_PROJECT_ID\": \"$OS_PROJECT_ID\",
      #     \"OS_PROJECT_NAME\": \"$OS_PROJECT_NAME\",
      #     \"OS_USER_DOMAIN_NAME\": \"$OS_USER_DOMAIN_NAME\",
      #     \"OS_PROJECT_DOMAIN_ID\": \"$OS_PROJECT_DOMAIN_ID\",
      #     \"OS_USERNAME\": \"$OS_USERNAME\",
      #     \"OS_PASSWORD\": \"$OS_PASSWORD\",
      #     \"OS_REGION_NAME\": \"$OS_REGION_NAME\"
      # }"

      echo "{
          \"OS_AUTH_URL\": \"$OS_AUTH_URL\"
      }"
    executable: /bin/bash
  register: output

- name: Set fact for vexxhost openrc
  set_fact:
    vexxhost_openrc: '{{ output.stdout | from_json }}'
