- hosts: all
  become: yes
  tasks:
    - name: Run Openshift functional tests against devstack
      shell:
        cmd: |
          set -e
          set -x
          git clone -b release-3.10 https://github.com/openshift/openshift-ansible.git
          cd openshift-ansible
          pip install "ansible>=2.6.5,<2.7"
          ansible --version
          ansible-playbook -i inventory/hosts.localhost playbooks/prerequisites.yml
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
