- hosts: all
  become: yes
  pre_tasks:
    - name: Prepare local conf for bosh acceptance testing requirements
      shell:
        cmd: |
          set -e
          set -x
          cat << EOF >> /tmp/dg-local.conf
          [[local|localrc]]
          NETWORK_GATEWAY=10.0.0.1
          IDENTITY_API_VERSION=3
          OS_USER_DOMAIN_ID=default
          OS_PROJECT_DOMAIN_ID=default
          VOLUME_BACKING_FILE_SIZE=80000M
          EOF
        executable: /bin/bash
  roles:
    - clone-devstack-gate-to-workspace
    - install-devstack
  tasks:
    - name: Run cloudfoundry acceptance tests of bosh-acceptance-tests
      shell:
        cmd: |
          sleep 10080
          curl -Lo ./bosh https://s3.amazonaws.com/bosh-cli-artifacts/bosh-cli-3.0.1-linux-amd64
          chmod +x ./bosh
          mv ./bosh /usr/local/bin/bosh
          bosh -v
          # apt-get install -y build-essential zlibc zlib1g-dev ruby ruby-dev openssl libxslt-dev libxml2-dev libssl-dev libreadline6 libreadline6-dev libyaml-dev libsqlite3-dev sqlite3

          mkdir bosh-1 && cd bosh-1
          git clone https://github.com/cloudfoundry/bosh-deployment.git
          source /opt/stack/new/devstack/openrc admin admin
          openstack keypair create microbosh > microbosh.pem
          openstack security group create bosh --description 'BOSH Security Group'
          openstack security group rule create --protocol tcp --ingress bosh

          mkdir bosh-openstack-kvm-ubuntu-trusty-go_agent
          pushd bosh-openstack-kvm-ubuntu-trusty-go_agent
          wget --content-disposition https://bosh.io/d/stemcells/bosh-openstack-kvm-ubuntu-trusty-go_agent -O bosh-openstack-kvm-ubuntu-trusty-go_agent.tgz
          tar -zxvf bosh-openstack-kvm-ubuntu-trusty-go_agent.tgz
          rm bosh-openstack-kvm-ubuntu-trusty-go_agent.tgz
          sed -i 's/kvm/qemu/g' stemcell.MF
          tar -zcvf bosh-openstack-qemu-ubuntu-trusty-go_agent.tgz *
          mv bosh-openstack-qemu-ubuntu-trusty-go_agent.tgz ../
          popd

          apt-get install ruby ruby-dev -y
          bosh create-env bosh-deployment/bosh.yml \
              --state=state.json \
              --vars-store=creds.yml \
              -o bosh-deployment/openstack/cpi.yml \
              -v director_name=bosh-1 \
              -v internal_cidr=10.0.0.0/24 \
              -v internal_gw=10.0.0.1 \
              -v internal_ip=10.0.0.6 \
              -v auth_url=${OS_AUTH_URL} \
              -v az=nova \
              -v default_key_name=microbosh \
              -v default_security_groups=[bosh] \
              -v net_id=$(openstack network show private -f value -c id) \
              -v openstack_password=${OS_PASSWORD} \
              -v openstack_username=${OS_USERNAME} \
              -v openstack_domain=${OS_USER_DOMAIN_ID} \
              -v openstack_project=${OS_TENANT_NAME} \
              -v private_key=/home/zuul/bosh-1/microbosh.pem \
              -v region=${OS_REGION_NAME}
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}'
