- hosts: all
  become: yes
  vars:
    job_uid: '{{ zuul.build[:10] }}'
  roles:
    - export-cloud-openrc
  tasks:
    - name: Clean up resources of openshift cluster on {{ cloud_name }}
      shell:
        cmd: |
          set -e
          set -x
          sleep 10800
          timeout 180 bash -c '
              while :
              do
                  openstack stack delete --wait --yes "openshift-{{ job_uid }}.openlab.com" && break
                  sleep 5
              done
              '
          openstack keypair delete "openshift-{{ job_uid }}"
          openstack volume delete `openstack volume list --status available -f value -c Name |grep kubernetes-dynamic-pvc`
        executable: /bin/bash
      environment: '{{ global_env }}'
