- hosts: all
  tasks:
    - name: install required packages
      become: true
      shell: |
        apt update -y
        apt install python python-pip python3 python3-pip kpartx qemu-utils curl python-yaml \
            debootstrap libffi-dev libssl-dev -y
        pip install ansible
      args:
        executable: /bin/bash

    - name: Create group account
      become: true
      group:
        name: "ubuntu"

    - name: Create ubuntu user account
      become: true
      user:
        createhome: true
        home: "/home/ubuntu"
        group: "ubuntu"
        name: "ubuntu"
        generate_ssh_key: yes

    - name: Register ubuntu pub key
      become: yes
      command: "cat /home/ubuntu/.ssh/id_rsa.pub"
      register: ubuntu_key
      no_log: yes

    - name: Create authorized_keys file
      become: yes
      file:
        path: "/home/ubuntu/.ssh/authorized_keys"
        group: ubuntu
        ower: ubuntu
        state: file
        mode: 0600

    - name: Ensure SSH public key is authorized
      become: true
      authorized_key:
        user: "ubuntu"
        key: "{{ ubuntu_key.stdout }}"
        path: "/home/ubuntu/.ssh/authorized_keys"

    - name: Run labkeeper functional test
      become: yes
      shell: |
        sudo cp /home/ubuntu/.ssh/id_rsa ./openlab.pem
        sudo chmod 600 openlab.pem
        export DPLOY_TYPE=test
        ansible-playbook playbooks/site.yaml -i inventory/test.yaml -e \
            "zuul_user_name=zuul-test zuul_user_group=zuul-test"
      args:
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
