- hosts: all
  become: yes
  tasks:
    - name: Clean up resources for kubernetes cinder acceptance tests
      shell:
        cmd: |
          set -e
          set -x
          kubectl="$GOPATH/src/k8s.io/kubernetes/cluster/kubectl.sh"
          "$kubectl" config use-context local
          "$kubectl" delete -f examples/persistent-volume-provisioning/cinder/cinder-in-tree-full.yaml
        executable: /bin/bash
        chdir: '{{ k8s_specific_src_dir }}'
      environment: '{{ golang_env }}'
