- hosts: all
  become: yes
  roles:
    - export-kubectl-env
    - start-k8s
  tasks:
    - name: Start testing
      shell:
        cmd: |
          set -x
          set -e
          set -o pipefail

          # Sleep to wait for creating serviceaccount default/default complete
          sleep 5
          # Remove node taint
          HOSTNAME_OVERRIDE=$(curl http://169.254.169.254/openstack/latest/meta_data.json | python -c "import sys, json; print json.load(sys.stdin)['name']")
          "$kubectl" taint nodes "$HOSTNAME_OVERRIDE" node.cloudprovider.kubernetes.io/uninitialized- || true
          # Cinder test
          "$kubectl" apply -f examples/persistent-volume-provisioning/cinder/cinder-in-tree-full.yaml

          # If test passed
          if timeout 100 bash -c '
              while :
              do
                  [[ $("$kubectl" describe pod web | awk "/^Status:/ {print \$2}") == Running ]] && break
                  sleep 1
              done
              '
          then
              echo 'Run test successful'
              "$kubectl" get pod
          else
              echo 'Run test failed'
              "$kubectl" get pod
              "$kubectl" describe pod
              exit 1
          fi
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ golang_env }}'
