- hosts: all
  become: yes
  pre_tasks:
    - shell:
        cmd: |
          set -e
          set -x
          cat << EOF >> /tmp/dg-local.conf
          [[local|localrc]]
          enable_plugin octavia https://git.openstack.org/openstack/octavia
          enable_plugin barbican https://git.openstack.org/openstack/barbican
          EOF
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'

  roles:
    - clone-devstack-gate-to-workspace
    - install-devstack
    - role: create-virtual-machines
      instance_name: instance_1
      private_key: private_key_1
  tasks:
    - shell:
        cmd: |
          set -e
          set -x
          set -o pipefail

          INSTANCE_NAME=instance_1
          PRIVATE_KEY=private_key_1

          source /opt/stack/new/devstack/openrc admin admin

          # Get floating ip by instance name
          INSTANCE_ID=$(openstack server show "$INSTANCE_NAME" -f value -c id)
          PORT_ID=$(openstack port list --device-id "$INSTANCE_ID" -f value -c id)
          FLOATING_IP=$(openstack floating ip list --port "$PORT_ID" -f value -c 'Floating IP Address')

          # Prepare env on executing node
          go get github.com/Masterminds/glide
          make depend

          # Remove env contains 'short_source' which is a function defined by devstack for formating PS4
          export -p | grep -v short_source > exported-envs

          # Sync into instance
          for rsync_dir in "$GOPATH"/{src,bin,pkg} /usr/local/go
          do
              rsync -az -e "ssh -i $PRIVATE_KEY" --rsync-path "sudo mkdir -p $rsync_dir && sudo rsync" "$rsync_dir"/ "ubuntu@$FLOATING_IP:$rsync_dir"
          done

          pip install -U ansible

          PROJECT_ID=$(openstack project show admin -f value -c id)
          SUBNET_ID=$(openstack subnet show lb-mgmt-subnet -f value -c id)
          FLOATING_NET_ID=$(openstack network show public -f value -c id)
          DEVSTACK_IP=$(ifconfig br-ex | grep "inet addr:" | awk '{print $2}' | cut -c 6-)

          ANSIBLE_ROLES_PATH={{ ansible_user_dir }}/src/github.com/liu-sheng/openlab-zuul-jobs/roles ansible-playbook -vvv \
              {{ ansible_user_dir }}/src/github.com/liu-sheng/openlab-zuul-jobs/playbooks/openstack-cloud-controller-manager-acceptance-test-lb-octavia/playbook-in-vm/run.yaml \
              -e server_name=instance_1 -e server_ip=$FLOATING_IP -e key_file=$(realpath privatekey_1) -e devstack_ip=$DEVSTACK_IP \
              -e ansible_user_dir="{{ ansible_user_dir }}" -e floating_network_id=$FLOATING_NET_ID -e project_id=$PROJECT_ID \
              -e subnet_id=$SUBNET_ID

        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ golang_env }}'
