- hosts: k8s-master
  become: yes
  tasks:
    - name: Collect k8s cluster and system components logs
      shell: |
        set -ex
        export KUBECONFIG=/etc/kubernetes/admin.conf
        mkdir -p '{{ k8s_log_dir }}/{{ item }}'
        pods=$(kubectl -n {{ item }} get pods -o jsonpath='{.items[*].metadata.name}')
        for pod in $pods; do
            for co in $(kubectl -n {{ item }} get pods $pod -o jsonpath='{.spec.containers[*].name}'); do
                kubectl -n {{ item }} logs $pod  -c $co > '{{ k8s_log_dir }}'/$pod-$co.log
            done
        done
      args:
        executable: /bin/bash
      with_items:
        - kube-system
        - kubeflow
        - volcano
