- hosts: all
  become: yes
  tasks:
    - shell:
        cmd: |
          set -e
          set -o pipefail
          set -x

          apt-get install ruby ruby-dev -y
          gem install bundler
          gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
          curl -L https://get.rvm.io | bash -s stable --rails
          /usr/local/rvm/scripts/rvm
          rvm list known
          bundle install --jobs=3 --retry=3
          bundle exec rake unit TESTOPTS='-v'
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
