- hosts: all
  become: yes
  tasks:
    - shell:
        cmd: |
          set -e
          set -o pipefail
          set -x

          apt-get install ruby ruby-dev -y

          gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
          curl -L https://get.rvm.io | bash -s stable --rails
          source /usr/local/rvm/scripts/rvm > /dev/null 2>&1

          for version in {{ rvm }};do
              rvm install ${version} --disable-binary > /dev/null 2>&1
              rvm use ${version} > /dev/null 2>&1
              echo "Running tests based on Ruby ${version}..."
              ruby --version
              gem install bundler
              bundle install --jobs=3 --retry=3
              bundle exec rake unit TESTOPTS='-v'
          done

        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
