# gophercloud
- name: install devstack with {{ os_branch }} for {{ sdk }}
  shell:
    cmd: |
      set -e
      set -x
      export PYTHONUNBUFFERED=true
      export GIT_BASE=https://github.com
      export OVERRIDE_ZUUL_BRANCH='{{ os_branch }}'
      cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
      ./safe-devstack-vm-gate-wrap.sh
    executable: /bin/bash
    chdir: '{{ ansible_user_dir }}/workspace'
  environment: '{{ zuul | zuul_legacy_vars }}'
  when:
    - sdk == 'gophercloud'
    - os_branch in stable_branches

- name: install devstack with {{ os_branch }} for {{ sdk }}
  shell:
    cmd: |
      set -e
      set -x
      export PYTHONUNBUFFERED=true
      export GIT_BASE=https://github.com
      export ZUUL_BRANCH=master
      export ZUUL_REF='refs/tags/{{ os_branch }}'
      export ZUUL_URL=https://github.com
      cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
      ./safe-devstack-vm-gate-wrap.sh
    executable: /bin/bash
    chdir: '{{ ansible_user_dir }}/workspace'
  environment: '{{ zuul | zuul_legacy_vars }}'
  when:
    - sdk == 'gophercloud'
    - os_branch in eol_branches

# terraform-provider-openstack
- name: install devstack with {{ os_branch }} for {{ sdk }}
  shell:
    cmd: |
      set -e
      set -x
      export PYTHONUNBUFFERED=true
      export GIT_BASE=https://github.com
      export OVERRIDE_ZUUL_BRANCH='{{ os_branch }}'
      export DEVSTACK_GATE_FIXED_RANGE=10.0.0.0/20
      # export PROJECTS=openstack/trove
      export PROJECTS="openstack/designate $PROJECTS"
      cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
      ./safe-devstack-vm-gate-wrap.sh
    executable: /bin/bash
    chdir: '{{ ansible_user_dir }}/workspace'
  environment: '{{ zuul | zuul_legacy_vars }}'
  when:
    - sdk == 'terraform-provider-openstack'
    - os_branch in stable_branches

- name: install devstack with {{ os_branch }} for {{ sdk }}
  shell:
    cmd: |
      set -e
      set -x
      export PYTHONUNBUFFERED=true
      export GIT_BASE=https://github.com
      export ZUUL_BRANCH=master
      export ZUUL_REF='refs/tags/{{ os_branch }}'
      export ZUUL_URL=https://github.com
      export DEVSTACK_GATE_FIXED_RANGE=10.0.0.0/20
      cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
      ./safe-devstack-vm-gate-wrap.sh
    executable: /bin/bash
    chdir: '{{ ansible_user_dir }}/workspace'
  environment: '{{ zuul | zuul_legacy_vars }}'
  when:
    - sdk == 'terraform-provider-openstack'
    - os_branch in eol_branches

# terraform
- name: install devstack with {{ os_branch }} for {{ sdk }}
  shell:
    cmd: |
      set -e
      set -x
      export PYTHONUNBUFFERED=true
      export GIT_BASE=https://github.com
      export OVERRIDE_ZUUL_BRANCH='{{ os_branch }}'
      cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
      ./safe-devstack-vm-gate-wrap.sh
    executable: /bin/bash
    chdir: '{{ ansible_user_dir }}/workspace'
  environment: '{{ zuul | zuul_legacy_vars }}'
  when:
    - sdk == 'terraform'
    - os_branch in stable_branches
