- hosts: all
  become: yes
  tasks:
    - name: Run ansible zuul job check tests for openlab-zuul-jobs
      shell:
        cmd: |
          set -e
          echo "hello"
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
