- hosts: all
  become: yes
  vars:
    sdk_ansible_tests_dirs:
      openstacksdk: '{{ ansible_user_dir }}/src/git.openstack.org/openstack/openstacksdk/openstack/tests/ansible'
      shade: '{{ ansible_user_dir }}/src/git.openstack.org/openstack-infra/shade/shade/tests/ansible'
  roles:
    - export-cloud-openrc
  tasks:
    - name: Create clouds.yaml of {{ cloud_name }}
      shell:
        cmd: |
          mkdir -p /etc/openstack/
          cat << EOF >> /etc/openstack/clouds.yaml
          clouds:
            {{ cloud_name }}:
              auth:
                username: {{ global_env.OS_USERNAME }}
                password: {{ global_env.OS_PASSWORD }}
                auth_url: {{ global_env.OS_AUTH_URL }}
                project_name: {{ global_env.OS_PROJECT_NAME }}
                project_domain_name: {{ global_env.OS_DOMAIN_NAME }}
                user_domain_name: {{ global_env.OS_DOMAIN_NAME }}
              identity_api_version: {{ global_env.OS_IDENTITY_API_VERSION }}
          EOF
        executable: /bin/bash

    - name: Install dependencies
      pip:
        name: "{{ item }}"
      with_items:
        - python-openstackclient
        - ansible

    - name: modify run.yml to allow ignoring errors per test case
      lineinfile:
        path: "{{ sdk_ansible_tests_dirs[os_sdk] }}/run.yml"
        insertafter: "^- hosts: localhost"
        line: "  ignore_errors: yes"

    - name: Run test cases
      shell: |
        export OS_CLOUD={{ cloud_name }}
        test_img=$(openstack image list -f value -c ID -c Name|grep Community_Ubuntu_16.04 | awk '{print $1}')
        ansible-playbook ./run.yml -e "cloud={{ cloud_name }} image=${test_img}" --tags "group,keypair"
      args:
        executable: /bin/bash
        chdir: "{{ sdk_ansible_tests_dirs[os_sdk] }}"
