- hosts: all
  become: yes
  roles:
    - config-golang
    - role: export-cloud-openrc
      vars:
        cloud_name: 'fusioncloud'
  tasks:
    - name: Run acceptance tests with terraform-provider-openstack against fusioncloud
      shell:
        cmd: |
          apt-get install python-pip -y
          pip install -U python-openstackclient

          export OS_SHARE_NETWORK_ID="foobar"
          export OS_FLAVOR_ID_RESIZE="s2.medium.2"
          export OS_FLAVOR_ID="s2.small.1"
          export OS_POOL_NAME="admin_external_net"
          export OS_EXTGW_ID="$(openstack network show $OS_POOL_NAME -f value -c id)"
          export OS_IMAGE_NAME="cirros-0.4.0-x86_64-disk"
          export OS_IMAGE_ID="$(openstack image show $OS_IMAGE_NAME -f value -c id)"
          export OS_NETWORK_NAME="openlab-jobs-net"
          export OS_NETWORK_ID="$(openstack network show openlab-jobs-net -f value -c id)"
          export OS_VPC_ID="$(openstack router show openlab-jobs-vpc -f value -c id)"

          set -e
          set -o pipefail
          set -x

          # Run except the DNS/FW/LB test 100 testcases at a time
          testcases=`go test ./openstack/ -v -list 'Acc'`
          testcases=`echo "$testcases" | sed '$d' | grep -v -e FW -e LB`
          echo "$testcases" | xargs -t -n100 sh -c 'TF_LOG=DEBUG TF_ACC=1 go test ./openstack -v -timeout 120m -run $(echo "$@" | tr " " "|")' argv0 2>&1 | tee $TEST_RESULTS_TXT
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ global_env }}'
