- name: Move '{{ zuul.project.short_name }}' to k8s specific directory
  shell:
    cmd: |
      set -x
      mkdir -p $(dirname '{{ k8s_repo_src_dir }}')
      mv '{{ zuul.project.src_dir }}' '{{ k8s_repo_src_dir }}'
    executable: /bin/bash
