- hosts: all
  become: yes

  tasks:
    - name: Copy bosh openstack cpi logs
      synchronize:
        src: '{{ ansible_user_dir }}/workspace/'
        dest: '{{ zuul.executor.log_root }}'
        mode: pull
        copy_links: true
        verify_host: true
        rsync_opts:
          - --include=/cpi-logs/**
          - --include=*/
          - --exclude=*
          - --prune-empty-dirs
