- name: Add server to inventory
  hosts: localhost
  become: yes
  tasks:
    - name: Add server ssh key
      command: "ssh-add {{ key_file }}"

    - name: Add server to inventory
      add_host:
        name: "{{ server_name }}"
        ansible_host: "{{ server_ip }}"
        ansible_user: "ubuntu"
        ansible_python_interpreter: /usr/bin/python3

- name: Prepare for local cluster
  hosts: "{{ server_name }}"
  become: yes
  gather_facts: no
  roles:
    - install-golang
  tasks:
    - shell:
        cmd: |
          set -e
          set -x
          echo 'testing...'
