- hosts: all
  become: yes
  roles:
    - clone-devstack-gate-to-workspace
    - create-devstack-local-conf
    - install-devstack
    - config-docker-machine
  tasks:
    - name: Create Docker machine
      shell:
        cmd: |
          set -ex
          set -o pipefail
          git clone https://github.com/sstephenson/bats.git
          pushd bats
          ./install.sh /usr/local
          popd
          # install Docker
          apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D || true
          apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D || true
          apt-add-repository 'deb http://apt.dockerproject.org/repo ubuntu-xenial main'
          apt-get update
          apt-cache policy docker-engine
          apt-get install -y docker-engine=1.12.6-0~ubuntu-xenial
          cat /lib/systemd/system/docker.service
          sed -r -i "s|(ExecStart)=(.+)|\1=\2 --iptables=false|" /lib/systemd/system/docker.service
          cat /lib/systemd/system/docker.service
          systemctl daemon-reload
          systemctl restart docker
          ifconfig -a

          pushd $GOPATH/src/github.com/docker/machine
          export OS_FLAVOR_ID=1
          export OS_IMAGE_NAME=$(openstack image list |grep -Eo "cirros.*-disk")
          sleep 7200
          docker-machine -D create -d openstack test1
          DEBUG=true VERBOSE=true DRIVER=openstack make test-integration test/integration/core
          popd
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ global_env }}'
