- hosts: all
  become: yes
  roles:
    - clone-devstack-gate-to-workspace
    - install-devstack
    - config-docker-machine
  tasks:
    - name: Create Docker machine
      shell:
        cmd: |
          set -ex
          set -o pipefail
          git clone https://github.com/sstephenson/bats.git
          pushd bats
          ./install.sh /usr/local
          popd
          pushd $GOPATH/src/github.com/docker/machine
          sleep 7200
          DEBUG=true VERBOSE=true DRIVER=openstack make test-integration test/integration/core/core-commands.bats
          popd
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ global_env }}'
