- hosts: all
  become: yes
  roles:
    - clone-devstack-gate-to-workspace
    - create-devstack-local-conf
    - install-devstack
  tasks:
    - name: Run cloudfoundry acceptance tests of cf-acceptance-tests
      shell:
        cmd: |
          sleep 10080
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
