- hosts: all
  pre_tasks:
    - name: Config DNS to fix unbound cache mechanism
      shell: echo "nameserver 8.8.8.8" >> /etc/resolv.conf
      args:
        executable: /bin/bash
      become: yes

  roles:
    - add-build-sshkey
    - start-zuul-console
    - validate-host
    - use-cached-repos
    - mirror-workspace-git-repos
#    - mirror-info
#    - configure-mirrors
    - role: fetch-zuul-cloner
      destination: "/usr/zuul-env/bin/zuul-cloner"
      repo_src_dir: "/home/zuul/src/github.com"
