---
- name: Install and config golang
  include_role:
    name: config-golang

- name: Compiled and install docker-machine from source
  shell:
    cmd: |
      set -ex

      # Install docker
      apt-get update
      apt-get install apt-transport-https ca-certificates
      wget -qO- https://get.docker.com/ | sh

      # NOTE: backport fix of PR 4543 and PR 4545
      git config --global user.email 'zuul@openlab.com'
      git config --global user.name 'openlab'
      git cherry-pick 9ec6729
      git cherry-pick 7909ee3

      # Build docker-machine
      make build
      cp ./bin/docker-machine /usr/local/bin/
      docker-machine version
    executable: /bin/bash
    chdir: '{{ zuul.project.src_dir }}'
  environment: '{{ global_env }}'
