- hosts: all
  become: yes
  roles:
    - export-kubectl-env
  tasks:
    - name: Clean up resources
      shell:
        cmd: |
          set -e
          set -x
          "$kubectl" config use-context local
          "$kubectl" delete -f examples/cinder-csi-plugin/nginx.yaml
          "$kubectl" delete -f manifests/cinder-csi-plugin
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ golang_env }}'
