- hosts: all
  become: yes
  roles:
    - install-k8s
  tasks:
    - name: Build cloud-provider-openstack binaries
      shell:
        cmd: |
          set -x
          set -e

          go get -u github.com/Masterminds/glide
          make build
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ golang_env }}'
