- hosts: all
  become: yes
  roles:
    - role: export-cloud-openrc
      vars:
        cloud_name: 'huaweicloud'
  tasks:
    - name: Clean up resources for cf-huaweicloud-validator tests
      shell:
        cmd: |
          set -e
          set -x
          openstack keypair delete cf-huaweicloud-validator-"{{ zuul.build }}" || true
        executable: /bin/bash
      environment: '{{ global_env }}'
