- hosts: all
  become: yes
  roles:
    - role: export-cloud-openrc
      vars:
        cloud_name: 'huaweicloud'
  tasks:
    - name: Run validation tests of cf-huaweicloud-validator aganist huaweicloud
      shell: |
        set -ex
        pip install python-openstackclient
        pip install python-glanceclient==2.11.0

        # Populate validator.yml
        openstack keypair create cf-huaweicloud-validator-"{{ zuul.build }}" > cf-validator.rsa_id
        FLOATING_IP=$(openstack floating ip create admin_external_net -f value -c floating_ip_address)
        _port_id=$(openstack port create --network openlab-jobs-net cf-huaweicloud-validator-port -f value -c id)
        STATIC_IP=$(openstack port show ${_port_id} -f value -c fixed_ips | grep -Eo '([0-9]+\.){3}[0-9]+')
        openstack port delete ${_port_id}
        NETWORK_ID=$(openstack network show openlab-jobs-net -f value -c id)
        INSTANCE_TYPE=$(openstack flavor list -f value -c ID -c RAM -c VCPUs --sort-column RAM --sort-column \
            VCPUs | awk '{if($2>=2048 && $3>=2){print $1}}' | head -n 1)

        set +x
        cp validator.template.yml validator.yml
        sed -i "/auth_url/ s|<replace-me>|$OS_AUTH_URL|" validator.yml
        sed -i "/username/ s|<replace-me>|$OS_USERNAME|" validator.yml
        sed -i "/password/ s|<replace-me>|$OS_PASSWORD|" validator.yml
        sed -i "/domain/ s|<replace-me>|$OS_DOMAIN_NAME|" validator.yml
        sed -i "/project/ s|<replace-me>|$OS_PROJECT_NAME|" validator.yml
        sed -i "/network_id/ s|<replace-me>|$NETWORK_ID|" validator.yml
        sed -i "/floating_ip/ s|<replace-me>|$FLOATING_IP|" validator.yml
        sed -i "/static_ip/ s|<replace-me>|$STATIC_IP|" validator.yml
        sed -i "/instance_type/ s|<replace-me>|$INSTANCE_TYPE|" validator.yml
        sed -i "/use_external_ip/ s|false|true|" validator.yml

        sed -i "/default_security_groups/ s|\[default\]|\[openlab-jobs-sg\]|" validator.yml
        sed -i "/default_key_name/ s|cf-validator|cf-huaweicloud-validator-{{ zuul.build }}|" validator.yml
        set -x

        # Download stemcell and change the hypervisor to qemu
        mkdir bosh-openstack-kvm-ubuntu-trusty-go_agent
        pushd bosh-openstack-kvm-ubuntu-trusty-go_agent
        wget --content-disposition https://bosh.io/d/stemcells/bosh-openstack-kvm-ubuntu-trusty-go_agent -O bosh-openstack-kvm-ubuntu-trusty-go_agent.tgz
        tar -zxvf bosh-openstack-kvm-ubuntu-trusty-go_agent.tgz
        rm bosh-openstack-kvm-ubuntu-trusty-go_agent.tgz
        sed -i 's/kvm/qemu/g' stemcell.MF
        tar -zcvf bosh-openstack-qemu-ubuntu-trusty-go_agent.tgz *
        mv bosh-openstack-qemu-ubuntu-trusty-go_agent.tgz ../
        popd

        chmod +x validate
        ./validate -s bosh-openstack-qemu-ubuntu-trusty-go_agent.tgz -c validator.yml
      args:
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/src/github.com/zhongjun2/cf-huaweicloud-validator'
      environment: '{{ global_env }}'
