- hosts: all
  become: yes
  roles:
    - role: export-cloud-openrc
      vars:
        cloud_name: 'huaweicloud'

  tasks:
    - name: Run validation tests of cf-huaweicloud-validator aganist huaweicloud
      shell: |
        set -ex
        sleep 7200

      args:
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
