- name: Deploy single-node k8s cluster by kubeadmin
  shell:
    cmd: |
      set -ex
      apt-get update && apt-get install -y apt-transport-https curl
      apt install -y docker.io

      curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
      cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
      deb https://apt.kubernetes.io/ kubernetes-xenial main
      EOF
      apt-get update
      apt-get install -y kubelet kubeadm kubectl
      apt-mark hold kubelet kubeadm kubectl

      systemctl daemon-reload
      systemctl restart kubelet.service
      sed -i 's/nameserver 127.0.0.1/nameserver 8.8.8.8/' /etc/resolv.conf

      echo 'Environment="KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/ --cni-bin-dir=/opt/cni/bin"' >> /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
      export KUBECONFIG=/etc/kubernetes/admin.conf
      kubeadm init --pod-network-cidr=192.168.0.0/16

      # Installing a pod network add-on
      kubectl apply -f https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml
      kubectl apply -f https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/kubernetes-datastore/calico-networking/1.7/calico.yaml
    executable: /bin/bash