- hosts: all
  become: yes
  tasks:
    - shell:
        cmd: |
          set -e
          set -o pipefail
          set -x

          apt-get install ruby ruby-dev -y
          sleep 7200
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
