- hosts: all
  become: yes
  roles:
    - export-cloud-openrc
    - config-docker-machine
  tasks:
    - name: Create Docker machine
      shell:
        cmd: |
          set -ex
          set -o pipefail
          git clone https://github.com/sstephenson/bats.git
          pushd bats
          ./install.sh /usr/local
          popd
          # install Docker
          apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D || true
          apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D || true
          apt-add-repository 'deb http://apt.dockerproject.org/repo ubuntu-xenial main'
          apt-get update
          apt-cache policy docker-engine
          apt-get install -y docker-engine=1.12.6-0~ubuntu-xenial
          cat /lib/systemd/system/docker.service
          sed -r -i "s|(ExecStart)=(.+)|\1=\2 --iptables=false|" /lib/systemd/system/docker.service
          cat /lib/systemd/system/docker.service
          systemctl daemon-reload
          systemctl restart docker
          ifconfig -a

          pip install python-openstackclient
          pip install python-glanceclient==2.11.0
          # Select a flavor have 2048M memory and 2 vCPU at least
          export OS_FLAVOR_ID=$(openstack flavor list -f value -c ID -c RAM -c VCPUs --sort-column RAM --sort-column \
              VCPUs | awk '{if($2>=2048 && $3>=2){print $1}}' | head -n 1)
          export OS_IMAGE_NAME="Ubuntu 16.04 Server 64bit"
          export OS_TENANT_ID=$(openstack token issue -f value -c project_id)
          export OS_NETWORK_NAME=openlab-jobs-net
          export OS_SSH_USER="ubuntu"
          export OS_FLOATINGIP_POOL="admin_external_net"
          export OS_SECURITY_GROUPS="openlab-jobs-sg"
          pushd $GOPATH/src/github.com/docker/machine
          # NOTE1: tests in test/integration/core/certs-extra-san.bats have references about boot2docker, which
          # probably only used by virtual box
          # NOTE2: tests in test/integration/core/crashreport.bats are only for virtualbox, skipped
          export DEBUG=true
          export VERBOSE=true
          export DRIVER=openstack
          make test-integration test/integration/core/scp.bats
          make test-integration test/integration/core/scp.bats
          make test-integration test/integration/core/core-commands.bats
          make test-integration test/integration/core/ssh-backends.bats
          make test-integration test/integration/core/engine-options.bats
          make test-integration test/integration/core/regenerate-certs.bats
          make test-integration test/integration/core/env_shell.bats
          make test-integration test/integration/core/inspect_format.bats
          make test-integration test/integration/core/swarm-options.bats
          popd
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ global_env }}'
