- hosts: all
  become: yes
  roles:
    - export-cloud-openrc
    - config-golang
  tasks:
    - name: Create Docker machine
      shell:
        cmd: |
          set -ex
          set -o pipefail
          git clone https://github.com/sstephenson/bats.git
          pushd bats
          ./install.sh /usr/local
          popd

          mkdir -p $GOPATH/src/github.com/docker/machine
          cp -r '{{ zuul.project.src_dir }}' $GOPATH/src/github.com/docker/
          pushd $GOPATH/src/github.com/docker/machine
          make build
          cp ./bin/docker-machine /usr/local/bin/
          docker-machine version
          popd

          pip install python-openstackclient
          pip install python-glanceclient==2.11.0
          # Select a flavor have 2048M memory and 2 vCPU at least
          export OS_FLAVOR_ID=$(openstack flavor list -f value -c ID -c RAM -c VCPUs --sort-column RAM --sort-column \
              VCPUs | awk '{if($2>=2048 && $3>=2){print $1}}' | head -n 1)
          export OS_IMAGE_NAME="Ubuntu 16.04 Server 64bit"
          export OS_TENANT_ID=$(openstack token issue -f value -c project_id)
          export OS_NETWORK_NAME=openlab-jobs-net
          export OS_SSH_USER="ubuntu"
          export OS_FLOATINGIP_POOL="admin_external_net"
          export OS_SECURITY_GROUPS="openlab-jobs-sg"
          export OS_SSH_USER="{{ ssh_user | default('ubuntu') }}"
          pushd $GOPATH/src/github.com/docker/machine
          DEBUG=true VERBOSE=true DRIVER=openstack make test-integration test/integration/core/
          popd
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ global_env }}'
