- hosts: all
  become: yes
  roles:
    - clone-devstack-gate-to-workspace
    - create-devstack-local-conf
    - install-devstack
  tasks:
    - name: Run validation tests of cf-openstack-validator aganist devstack
      shell:
        cmd: |
          set -e
          set -o pipefail
          set -x
          sleep 7200

        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
