- hosts: all
  become: yes
  pre_tasks:
    - name: Install python-pip
      shell:
        cmd: |
          echo 'pip!=8,<10.0.0' > /opt/stack/new/devstack/tools/cap-pip.txt
          # https://review.openstack.org/#/c/562610/
        executable: /bin/bash
  roles:
    - clone-devstack-gate-to-workspace
    - create-devstack-local-conf
    - install-devstack
  tasks:
    - name: Run validation tests of cf-openstack-validator aganist devstack
      shell:
        cmd: |
          set -e
          set -o pipefail
          set -x
          sleep 7200

        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
