- hosts: all
  become: yes
  roles:
    - clone-devstack-gate-to-workspace
    - create-devstack-local-conf
    - role: install-devstack
      environment:
        WSGI_MODE: mod_wsgi
  tasks:
    - name: Run validation tests of cf-openstack-validator aganist devstack
      shell:
        cmd: |
          set -x
          sleep 7200

          source /opt/stack/new/devstack/openrc admin admin
          floating_ip=$(openstack floating ip create public -f value -c floating_ip_address)
          static_ip=10.0.0.50
          neutron port-create --fixed-ip subnet_id=private-subnet,ip_address="$static_ip" --name static_ip private
          security_group_id=$(openstack security group list | awk "/$(openstack project show admin -f value -c id)/ {print \$2}")
          openstack security group rule create --ingress --protocol tcp --dst-port 22 "$security_group_id"
          ssh-keygen -t rsa -b 4096 -N '' -f cf-validator.rsa_id
          openstack keypair create cf-validator --public-key cf-validator.rsa_id.pub
          apt install ruby-full -y
          gem install bundler
          bundle install
          wget --content-disposition https://bosh.io/d/stemcells/bosh-openstack-kvm-ubuntu-trusty-go_agent
          cp validator.template.yml validator.yml
          ./validate --stemcell bosh-stemcell-3586.5-openstack-kvm-ubuntu-trusty-go_agent.tgz --config validator.yml
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
