- name: Create AI environment and train
  shell:
    cmd: |
      set -x
      set -e
      apt install unzip python-pip -y

      result_folder="{{ ansible_user_dir }}/workspace/test_results/"
      mkdir -p $result_folder

      user_data_folder='{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/user_data/'

      if ls $user_data_folder | grep txt;then
        txt_file=`ls $user_data_folder | grep txt`
        url=`cat $user_data_folder$txt_file`
        wget $url -O $user_data_folder
      fi

      zip_file=`ls $user_data_folder | grep zip`

      unzip $user_data_folder$zip_file -d $user_data_folder

      pip install tensorflow

      py_file=`ls $user_data_folder | grep py`
      python $user_data_folder$py_file | tee ${result_folder}"/model_log.txt"

    executable: /bin/bash
