- name: Create AI Environment
  shell:
    cmd: |
      set -x
      set -e

      apt install -y unzip python-pip
      pip install pyyaml

      result_folder="{{ ansible_user_dir }}/workspace/test_results/"
      mkdir -p $result_folder

      user_data_folder='{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/user_data/'
      cd $user_data_folder

      if ls | grep txt;then
        txt_file=`ls | grep txt`
        url=`cat $txt_file`
        wget $url
      fi

      zip_file=`ls | grep zip`

      unzip $zip_file

      python '{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/tools/analysis_yaml.py'
    executable: /bin/bash

- name: Get Runtime Name
  shell: cat '{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/user_data/framework_runtime.txt'
  register: runtime

- name: Install Python Runtime
  when: runtime.stdout.find('python') != -1
  shell: apt install -y python2.7 python3.5 python3.6 python3.7
  register: is_python_runtime

- name: Get Framework Name
  shell: cat '{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/user_data/framework_name.txt'
  register: framework

- name: Run Tensorflow Python Job
  when: framework.stdout == "tensorflow" and is_python_runtime is defined
  shell:
    cmd: |
      set -x
      set -e

      user_data_folder='{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/user_data/'
      cd $user_data_folder

      version=`cat framework_version.txt`

      pip install tensorflow==${version}

      py_file=`cat entry_point.txt`

      result_folder="{{ ansible_user_dir }}/workspace/test_results/"

      '{{ runtime.stdout }}' $py_file | tee ${result_folder}"/process_log.txt"
    executable: /bin/bash

- name: Run PyTorch Python Job
  when: framework.stdout == "pytorch" and is_python_runtime is defined
  shell:
    cmd: |
      set -x
      set -e

      user_data_folder='{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/user_data/'
      cd $user_data_folder

      version=`cat framework_version.txt`

      pip install torch==${version} torchvision

      py_file=`cat entry_point.txt`

      result_folder="{{ ansible_user_dir }}/workspace/test_results/"

      '{{ runtime.stdout }}' python $py_file | tee ${result_folder}"/process_log.txt"
    executable: /bin/bash

- name: Check output folder variable exists
  stat:
    path: '{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/user_data/output_folder.txt'
  register: stat_ouput_folder_variable

- name: Get output folder variable value
  when: stat_ouput_folder_variable.stat.exists
  shell: cat '{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/user_data/output_folder.txt'
  register: output_folder_name

- name: Check output folder exists
  stat:
    path: '{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/user_data/{{ output_folder_name.stdout }}'
  register: stat_ouput_folder

- name: Collect Traning or Inference Result if needed
  when: stat_ouput_folder.stat.exists and stat_ouput_folder.stat.isdir
  shell:
    cmd: |
      set -x
      set -e

      mv '{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/user_data/{{ output_folder_name.stdout }}' \
        '{{ ansible_user_dir }}/workspace/test_results/'
