- name: Create AI environment and train
  shell:
    cmd: |
      set -x
      set -e
      apt install unzip python-pip -y

      result_folder="{{ ansible_user_dir }}/workspace/test_results/"
      mkdir -p $result_folder

      user_data_folder='{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/user_data/'
      cd $user_data_folder

      if ls | grep txt;then
        txt_file=`ls | grep txt`
        url=`cat $txt_file`
        wget $url
      fi

      zip_file=`ls | grep zip`

      unzip $zip_file

      pip install tensorflow

      py_file=`ls | grep py`
      python $py_file | tee ${result_folder}"/model_log.txt"

    executable: /bin/bash
