- name: Create AI environment and train
  shell:
    cmd: |
      set -x
      set -e

      apt install unzip python-pip -y
      pip install yaml

      result_folder="{{ ansible_user_dir }}/workspace/test_results/"
      mkdir -p $result_folder

      user_data_folder='{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/user_data/'
      cd $user_data_folder

      if ls | grep txt;then
        txt_file=`ls | grep txt`
        url=`cat $txt_file`
        wget $url
      fi

      zip_file=`ls | grep zip`

      unzip $zip_file

      python '{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/tools/analysis_yaml.py'

      head -n 1 metadata.txt |tail -n 1
    executable: /bin/bash
  register: framework

- name: Tensorflow framework
  when: "framework==tensorflow"
  shell:
    cmd: |
      set -x
      set -e

      version = head -n 2 metadata.txt |tail -n 1

      pip install tensorflow==${version}

      py_file=head -n 3 metadata.txt |tail -n 1

      python $py_file | tee ${result_folder}"/model_log.txt"
    executable: /bin/bash

