- name: Create AI environment and train
  shell:
    cmd: |
      set -x
      set -e

      mkdir /opt/aitest
      mkdir -p "{{ ansible_user_dir }}/workspace/test_results/"

      folder_name='{{ ansible_user_dir }}/{{ zuul.project.src_dir }}/user_data/'
      file_name=`ls $folder_name | grep zip`

      apt install unzip -y

      unzip $folder_name$file_name -d /opt/aitest

      apt install -y python-pip

      pip install tensorflow

      python /opt/aitest/tensorflow_test.py

    executable: /bin/bash
