- name: Set up Kubernetes local cluster
  hosts: all
  become: yes
  pre_tasks:
    - name: Configuration before starting k8s services
      shell:
        cmd: |
          # Create webhook.kubeconfig
          mkdir -p /etc/kubernetes/
          cat << EOF >> /etc/kubernetes/webhook.kubeconfig
          apiVersion: v1
          clusters:
          - cluster:
              insecure-skip-tls-verify: true
              server: https://localhost:8443/webhook
            name: webhook
          contexts:
          - context:
              cluster: webhook
              user: webhook
            name: webhook
          current-context: webhook
          kind: Config
          preferences: {}
          users:
          - name: webhook
          EOF

          STARTUP_SCRIPT="$GOPATH/src/k8s.io/kubernetes/hack/local-up-cluster.sh"
          sed -i -e "/kube::util::wait_for_url.*$/,+1d" "$STARTUP_SCRIPT"
          sed -i -e '/hyperkube\" apiserver.*$/a \      --authentication-token-webhook-config-file=/etc/kubernetes/webhook.kubeconfig \\' "$STARTUP_SCRIPT"
          sed -i -e '/hyperkube\" apiserver.*$/a \      --authorization-webhook-config-file=/etc/kubernetes/webhook.kubeconfig \\' "$STARTUP_SCRIPT"
        executable: /bin/bash
      environment: '{{ golang_env }}'
  roles:
    - export-kubectl-env
    - export-vexxhost-openrc
    - role: start-k8s-services
      environment:
        AUTHORIZATION_MODE: 'Node,Webhook,RBAC'
  tasks:
    - name: Start testing
      shell:
        cmd: |
          set -x
          set -e
          set -o pipefail

          mkdir -p /etc/kubernetes/
          cp ./examples/webhook/policy.json /etc/kubernetes/
          sed -i "s/c1f7910086964990847dc6c8b128f63c/$OS_PROJECT_ID/g" /etc/kubernetes/policy.json
          sed -i -e "s/k8s-admin/creator/g" /etc/kubernetes/policy.json

          LOG_DIR='{{ ansible_user_dir }}/workspace/logs/kubernetes'
          nohup ./k8s-keystone-auth \
                --tls-cert-file /var/run/kubernetes/serving-kube-apiserver.crt \
                --tls-private-key-file /var/run/kubernetes/serving-kube-apiserver.key \
                --keystone-policy-file /etc/kubernetes/policy.json \
                --log-dir="$LOG_DIR" \
                --v=10 \
                --keystone-url "$OS_AUTH_URL" \
                > "$LOG_DIR/keystone-auth.log" 2>&1 &

          apt-get install python-pip -y
          pip install -U python-openstackclient

          {
              authenticated_info=$(cat <<< '
                  {
                    "apiVersion": "authentication.k8s.io/v1beta1",
                    "kind": "TokenReview",
                    "metadata": {
                        "creationTimestamp": null
                    },
                    "spec": {
                        "token": "'$(openstack token issue -f value -c id)'"
                    }
                  }' | curl -kvs -XPOST -d @- https://localhost:8443/webhook | python -c "import sys, json; print json.load(sys.stdin)"
              )
              base_body=$(cat <<< '
                  {
                      "apiVersion": "authorization.k8s.io/v1beta1",
                      "kind": "SubjectAccessReview",
                      "spec": {
                          "resourceAttributes": {
                              "namespace": "default",
                              "verb": "get",
                              "group": "",
                              "resource": "pods"
                          }
                      }
                  }' |  python -c "import sys, json; print json.load(sys.stdin)"
              )
              update_auth_info=$(echo "
                  import json;
                  s1=$authenticated_info;
                  s2=$base_body;
                  s2['spec']['user']=s1['status']['user']['username'];
                  s2['spec']['group']=s1['status']['user']['groups'];
                  s2['spec']['extra']=s1['status']['user']['extra'];
                  print json.dumps(s2)" | sed 's/^ \+//'
              )
              authorization_body=$(python -c "$update_auth_info")
              allowed=$(echo "$authorization_body" | curl -kvs -XPOST -d @- https://localhost:8443/webhook | python -mjson.tool)
          } > /dev/null 2>&1

          echo "$allowed"
          [[ "$allowed" =~ '"allowed": true' ]] && echo "Testing k8s-keystone-auth sucessfully!"

          "$kubectl" config set-credentials openstackuser --auth-provider=openstack
          "$kubectl" config set-context --cluster=local --user=openstackuser openstackuser@local
          "$kubectl" config use-context openstackuser@local
          if ! "$kubectl" get pod; then
              echo "Testing kubernetes+keystone authentication and authorizatio failed!"
              exit 1
          fi
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ golang_env }}'
