- name: Create tensorflow pod
  shell:
    cmd: |
      set -x
      set -e

      mkdir /opt/aitest

      wget https://raw.githubusercontent.com/wangxiyuan/ai-openlab-test/master/tensorflow_test.py \
        -O /opt/aitest/tensorflow_test.py

      cat > "/opt/aitest/test.yml" <<EOF
      apiVersion: v1
      kind: Pod
      metadata:
        name: ai-test
      spec:
        containers:
        - name: ai-tensorflow-cpu
          image: tensorflow/tensorflow
          ports:
          - containerPort: 7777
          command: ["/usr/local/bin/python"]
          args: ["/test/tensorflow_test.py"]
          volumeMounts:
          - mountPath: /test/
            name: exec
            readOnly: true
        hostNetwork: true
        volumes:
        - hostPath:
            path: /opt/aitest
            type: DirectoryOrCreate
          name: exec
      EOF

      if ! timeout 30 sh -c "while ! kubectl get sa|grep default; do sleep 1; done"; then
        exit 1
      fi

      export KUBECONFIG=/etc/kubernetes/admin.conf
      kubectl create -f /opt/aitest/test.yml


    executable: /bin/bash
