- hosts: all
  become: yes
  pre_tasks:
    - shell:
        cmd: |
          set -e
          set -x
          cat << EOF >> /tmp/dg-local.conf
          [[local|localrc]]
          ETCD_DOWNLOAD_URL=https://github.com/coreos/etcd/releases/download
          ETCD_VERSION=v3.3.0
          ETCD_SHA256=d91efb17ab0813039e24863a1af154b153d4b1a009181d6faa18e8ab681676dc
          NETWORK_GATEWAY=10.0.0.1
          enable_plugin octavia https://git.openstack.org/openstack/octavia
          enable_plugin barbican https://git.openstack.org/openstack/barbican
          enable_plugin openstack-cloud-controller-manager https://github.com/dims/openstack-cloud-controller-manager
          EOF
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
  roles:
    - clone-devstack-gate-to-workspace
    - role: install-devstack
      environment:
        ENABLED_SERVICES: 'octavia,o-cw,o-hm,o-hk,o-api'
        PROJECTS: "openstack/barbican openstack/python-barbicanclient liu-sheng/openstack-cloud-controller-manager"
  tasks:
    - shell:
        cmd: |
          set -e
          set -x
          set -o pipefail
          source /opt/stack/new/devstack/openrc admin admin
          add-apt-repository ppa:masterminds/glide -y
          apt-get update -y
          apt-get install glide -y
          sleep 7200
          TESTARGS='-v' make test 2>&1 | tee $TEST_RESULTS_TXT
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ golang_env }}'
