- hosts: all
  become: yes
  roles:
    - clone-devstack-gate-to-workspace
    - create-devstack-local-conf
    - role: install-devstack
      environment:
        OVERRIDE_ENABLED_SERVICES: 'c-api,c-bak,c-sch,c-vol,cinder,dstat,etcd3,g-api,g-reg,key,mysql,n-api,n-api-meta,n-cauth,n-cond,n-cpu,n-novnc,n-obj,n-sch,peakmem_tracker,placement-api,q-agt,q-dhcp,q-l3,q-meta,q-metering,q-svc,rabbit'
        GIT_BASE: 'https://github.com'
  tasks:
    - shell:
        cmd: |
          set -e
          set -x
          add-apt-repository ppa:masterminds/glide -y
          apt-get update -y
          source /opt/stack/new/devstack/openrc admin admin
          apt-get install glide
          go get ./... || true
          make test
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ golang_env }}'
