- hosts: all
  become: yes
  roles:
    - deploy-k8s-cluster-kubeadm
  tasks:
    - name: Test functionalities of Spark deployed on k8s cluster
      shell: |
        git clone http://github.com/kubernetes/examples
        sleep 7200
        create -f examples/staging/spark/
        kubectl get pods
        kubectl get svc -o wide

        #######################
        kubectl create -f examples/staging/spark/namespace-spark-cluster.yaml
        kubectl get namespaces
        CURRENT_CONTEXT=$(kubectl config view -o jsonpath='{.current-context}')
        USER_NAME=$(kubectl config view -o jsonpath='{.contexts[?(@.name == "'"${CURRENT_CONTEXT}"'")].context.user}')
        CLUSTER_NAME=$(kubectl config view -o jsonpath='{.contexts[?(@.name == "'"${CURRENT_CONTEXT}"'")].context.cluster}')
        kubectl config set-context spark --namespace=spark-cluster --cluster=${CLUSTER_NAME} --user=${USER_NAME}
        kubectl config use-context spark
      args:
        executable: /bin/bash
