- hosts: all
  become: yes
  roles:
    - deploy-k8s-cluster-kubeadm
  tasks:
    - name: Test functionalities of Spark deployed on k8s cluster
      shell: |
        sleep 7200

      args:
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
