- hosts: all
  become: yes
  roles:
    #- export-vexxhost-openrc
    - export-opentelekomcloud-openrc
  tasks:
    - name: Run unit tests with cloud-provider-openstack
      shell:
        cmd: |
          set -x
          set -e
          set -o pipefail

          go get -u github.com/Masterminds/glide
          cd "$GOPATH/src/k8s.io/cloud-provider-openstack"
          TESTARGS='-v' make test 2>&1 | tee $TEST_RESULTS_TXT
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ golang_env | combine(vexxhost_openrc) }}'
