- hosts: all
  become: yes
  tasks:
    - shell:
        cmd: |
          # NOTE: the following commands may include sensitive information please do not print in job logs
          export OS_AUTH_TYPE='{{ vexxhost_credentials.auth_type }}'
          export OS_IDENTITY_API_VERSION='{{ vexxhost_credentials.identity_api_version }}'
          export OS_VOLUME_API_VERSION='{{ vexxhost_credentials.volume_api_version }}'
          export OS_INTERFACE='{{ vexxhost_credentials.interface }}'
          export OS_AUTH_URL='{{ vexxhost_credentials.auth_url }}'
          export OS_PROJECT_ID='{{ vexxhost_credentials.project_id }}'
          export OS_PROJECT_NAME='{{ vexxhost_credentials.project_name }}'
          export OS_USER_DOMAIN_NAME='{{ vexxhost_credentials.user_domain_name }}'
          export OS_PROJECT_DOMAIN_ID='{{ vexxhost_credentials.project_domain_id }}'
          export OS_USERNAME='{{ vexxhost_credentials.username }}'
          export OS_PASSWORD='{{ vexxhost_credentials.password }}'
          export OS_REGION_NAME='{{ vexxhost_credentials.region_name }}'

          set -x
          set -e
          set -o pipefail
          go get -u github.com/Masterminds/glide
          TESTARGS='-v' make test 2>&1 | tee $TEST_RESULTS_TXT
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ golang_env }}'
