- hosts: all
  become: yes
  tasks:
    - name: Build containerd
      shell:
        cmd: |
          set -xe
          apt-get update
          apt-get install -y btrfs-tools libseccomp-dev git pkg-config
          apt-get install -y golang-1.10-go
          ln -s ../lib/go-1.10/bin/go /usr/bin/go

          go get github.com/containerd/containerd
          cd ~/go/src/github.com/containerd/containerd/
          make
          make test
        executable: /bin/bash
