- hosts: all
  become: yes
  roles:
    - config-packer
    - export-cloud-openrc
  tasks:
    - name: Create image by Packer
      shell:
        cmd: |
          set -ex
          set -o pipefail
          pip install python-openstackclient
          pip install python-glanceclient==2.11.0
          flavor=$(openstack flavor list -f value -c ID -c RAM -c VCPUs --sort-column RAM --sort-column VCPUs | head -n 1 | awk '{print $1}')
          network=$(openstack network show openlab-net -f value -c id)
          image_name="packer-linux-openstack-demo-$(date +%s)"

          cat << EOF >> welcome.txt
          WELCOME TO PACKER!
          EOF

          cat << EOF >> os-template.json
          {
              "builders": [
                  {
                      "type": "openstack",
                      "flavor": "$flavor",
                      "image_name": "$image_name",
                      "source_image_name": "Community_Ubuntu_16.04_TSI_latest",
                      "ssh_username": "ubuntu",
                      "networks": ["$network"]
                  }
              ],
              "provisioners": [
                  {
                      "type": "file",
                      "source": "./welcome.txt",
                      "destination": "/home/ubuntu/"
                  },
                  {
                      "type": "shell",
                      "inline":[
                          "ls -al /home/ubuntu",
                          "cat /home/ubuntu/welcome.txt"
                      ]
                  }
              ]
          }
          EOF
          packer validate os-template.json
          packer build -color=false os-template.json
          openstack image show $image_name
          openstack image delete $image_name
        executable: /bin/bash
      environment: '{{ global_env }}'
