- hosts: all
  become: yes
  roles:
    - config-golang
    - export-cloud-openrc
  tasks:
    - name: Create image by packer
      shell:
        cmd: |
          sleep 7200
        executable: /bin/bash
