- hosts: all
  become: yes
  roles:
    - config-golang
    - export-cloud-openrc
  tasks:
    - name: Create image by Packer
      shell:
        cmd: |
          set -ex
          set -o pipefail
          mv $GOPATH/src/github.com/liu-sheng/packer $GOPATH/src/github.com/hashicorp/packer || true
          cd $GOPATH/src/github.com/hashicorp/packer
          go get ./...
          go build -o bin/packer .
          sleep 7200
        executable: /bin/bash
      environment: '{{ global_env }}'
