- hosts: all
  become: yes
  roles:
    - config-golang
    - export-cloud-openrc
  tasks:
    - name: Create image by Packer
      shell:
        cmd: |
          set -ex
          set -o pipefail
          pip install python-openstackclient
          mkdir -p $GOPATH/src/github.com/hashicorp/
          mv $GOPATH/src/github.com/liu-sheng/packer $GOPATH/src/github.com/hashicorp/packer || true
          cd $GOPATH/src/github.com/hashicorp/packer
          go get ./...
          make dev
          packer version
          flavor=$(openstack flavor list -f value -c ID -c RAM -c VCPUs --sort-column RAM --sort-column VCPUs | head -n 1 | awk '{print $1}')
          network=$(openstack network show openlab-net -f value -c id)

          cat << EOF >> welcome.txt
          WELCOME TO PACKER!
          EOF
          cat << EOF >> example.sh
          #!/bin/bash
          echo "hello"
          EOF

          cat << EOF >> os-template.json
          {
              "builders": [
                  {
                      "type": "openstack",
                      "flavor": "$flavor",
                      "image_name": "packer-linux-openstack-demo",
                      "source_image_name": "Community_Ubuntu_16.04_TSI_latest",
                      "networks": ["$network"]
                  }
              ],
              "provisioners": [
                  {
                      "type": "file",
                      "source": "./welcome.txt",
                      "destination": "/home/ubuntu/"
                  },
                  {
                      "type": "shell",
                      "inline":[
                          "ls -al /home/ubuntu",
                          "cat /home/ubuntu/welcome.txt"
                      ]
                  },
                  {
                      "type": "shell",
                      "script": "./example.sh"
                  }
              ]
          }
          EOF
          packer build os-template.json
          openstack image show packer-linux-openstack-demo
          openstack image delete packer-linux-openstack-demo
        executable: /bin/bash
      environment: '{{ global_env }}'
